name: dex-ui CI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  docker_build_and_deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set var for getting tag or branch
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}:${{ steps.vars.outputs.tag }}

      - name: Configure ssh
        run: |
          mkdir ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/devapp
          chmod 600 ~/.ssh/devapp
          cat >> ~/.ssh/config << END
          Host devapp
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/devapp
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: root
          SSH_KEY: ${{ secrets.SSH_SECRET }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Pull and run docker on server
        run: |
          ssh devapp "docker pull $IMG_TAG"
          ssh devapp "cd $W_DIR; git fetch --tags; git checkout $REPOS_TAG"
          ssh devapp "bash -ic 'cd $W_DIR; npm i; npm run prod -- $IMG_TAG'"
        env:
          IMG_TAG: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}:${{ steps.vars.outputs.tag }}
          W_DIR: ${{ github.event.repository.name }}
          REPOS_TAG: ${{ steps.vars.outputs.tag }}
